title: "DSC180A Methodology Assignment 5"
author: "Angelina Zhang"
email: "ruz039@ucsd.edu"
description: "Static site for answering prompts for Methodology Assignment 5"
theme: jekyll-theme-architect
